### ISSUE TITLE
uncomplete code

### ISSUE THREAD

**Issue by cunese0666** [youmi-zym/AcfNet#4]
First,thanks for your outstanding work, open source spirit and the patience to the problem.Would you please push the complete code on github?Can you provide the train files?
And I also try to repo the acfnet according to the DensematchingBenchmark.
**Describe the bug**
When I use 'python tools/train.py configs xxx ', this error happened.
  File "tools/train.py", line 55, in main
    cfg = Config.fromfile(args.config)
  File "/home/anaconda3/envs/dmn/lib/python3.7/site-packages/mmcv/utils/config.py", line 211, in fromfile
    use_predefined_variables)
  File "/home//anaconda3/envs/dmn/lib/python3.7/site-packages/mmcv/utils/config.py", line 142, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/anaconda3/envs/dmn/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpvmtj58zj/tmpdbc_zg73.py", line 147, in <module>
NameError: name 'vis_data_root' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fee72522200>
Traceback (most recent call last):
  File "/home/anaconda3/envs/dmn/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/anaconda3/envs/dmn/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvmtj58zj/tmpdbc_zg73.py'
**Environment**
python 3.7  pytorch 1.5  GCC4.6.5  cuda10.2 mmcv 0.4.4

**Comment by youmi-zym** [comment]
Hi,
Thanks for your interest in our work. The bug is: **NameError: name 'vis_data_root' is not defined**. Due to some reasons, we force the config file to contain 'vis_data_root' for visualization. Maybe we will remove such constraint in the future.

So, to solve your problem,  you can download the 'visualization data' for [here](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/DATA.md#prepare-visualization-dataset), and pass the data root to config file.

Hope everything is fine!

**Comment by cunese0666** [comment]
During the reproduction process, according to the config file,I can't training successfully. Will you open source the train.py file under the ACFNet project? 
I tried to supplement the training file myself, but the effect was not very good.
Hope for getting your reply!

**Comment by youmi-zym** [comment]
Hi, 
I'm sorry for these troubles. Because the AcfNet project is extracted from [DenseMatchingBenchmark](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark), it's hard to provide another training script.

So, there are two options I can help with:
1. use the [DenseMatchingBenchmark](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark) for training, and according to the [GetStarted](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark#get-started) to get started, or run a [demo](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/GETTING_STARTED.md#run-a-demo) to get the details of our model quickly, and then you can build a model with our code and train with other project's script, such as PSMNet.
2. upload your code here and I'll help you check bug
